#!/bin/sh
set -e

help() {
  echo "Usage: shvm fetch <target>"
}

force=
target=

while test $# != 0; do
  case "$1" in
  --help)
    help
    exit 0
    ;;
  -f|--force)
    force=t
    ;;
  -*|--*)
    echo >&2 "Unrecognized option: $1"
    exit 1
    ;;
  *)
    target="$1"
    ;;
  esac
  shift
done

IFS='-' read -r target_type target_version<<EOF
$target
EOF

if [ -z "$target_type" ] || [ -z "$target_version" ]; then
  help
  exit 1
fi

if [ -z "$force" ] && [ -d "$SHVM_HOME/src/$target" ]; then
  echo "The source of $target is already exists"
  return 0
fi

if [ ! -d "$SHVM_HOME/usr/${target_type}-support" ] || [ ! -x "$SHVM_HOME/usr/${target_type}-support/fetch" ]; then
  echo "$target_type not supported"
  exit 1
fi

echo "Fetching ${target}..."
"$SHVM_HOME/usr/${target_type}-support/fetch" "$target"
