#!/bin/sh
set -e

abort() {
  echo "$@" >&2
  exit 1
}

help() {
  echo "Usage: shvm install <target>"
}

target=

while test $# != 0; do
  case "$1" in
  --help)
    help
    exit 0
    ;;
  -*|--*)
    echo >&2 "Unrecognized option: $1"
    exit 1
    ;;
  *)
    target="$1"
    ;;
  esac
  shift
done

if [ -z "$target" ]; then
  help
  exit 1
fi

if [ -d "$SHVM_HOME/usr/$target" ]; then
  echo "$target installed"
  return 0
fi

$SHVM_HOME/usr/shvm-core/shvm-fetch "$target" || exit 1

builddir=$(mktemp -d)
( cd "$builddir"

  echo "Checking build system..."
  "$SHVM_HOME/src/$target/configure" \
    --prefix="$SHVM_HOME/usr/$target" 2>/dev/tty >/dev/null \
    || abort "Failed to configure $target}.
Make sure that '$SHVM_HOME/src/$target --prefix=$SHVM_HOME/usr/$target' \
succeeds before install"

  echo "Building ${target}..."
  make -C "$builddir" install >/dev/null 2>&1 \
    || abort "Failed to build ${target}.
Make sure that 'make -C $builddir install' succeeds before install"
)

rm -rf "$builddir"
echo "$target installed"

