#!/bin/sh
set -e

[ -z "$1" ] && exit 1

abort() {
  echo "$@" >&2
  exit 1
}

(
  cd "$SHVM_HOME/src/$1"

  echo "Checking build system..."

  autoconf
  ./configure --prefix="$SHVM_HOME/lib/$1" 2>/dev/tty >/dev/null ||\
    abort "Failed to configure $1}.
Make sure that 'cd \$SHVM_HOME/src/$1; ./configure --prefix=$SHVM_HOME/lib/$1' \
succeeds before install"

  echo "Building ${1}..."
  make install >/dev/null 2>&1 ||\
    abort "Failed to build ${1}.
Make sure that 'cd \$SHVM_HOME/src/$1; make install' succeeds before install"
)
